apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "beechart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      
  selector:
    {{- include "beechart.selectorLabels" . | nindent 4 }}
